--废柴女神阿库娅
function c74010009.initial_effect(c)
	c:SetUniqueOnField(1,0,74010009)
	c:EnableReviveLimit()
	--ritual material
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetCode(EFFECT_EXTRA_RITUAL_MATERIAL)
	e1:SetValue(1)
	c:RegisterEffect(e1)
	--atk/def
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_SINGLE)
	e3:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e3:SetRange(LOCATION_MZONE)
	e3:SetCode(EFFECT_UPDATE_ATTACK)
	e3:SetValue(600)
	e3:SetCondition(c74010009.effcon)
	e3:SetLabel(2)
	c:RegisterEffect(e3)
	local e4=e3:Clone()
	e4:SetCode(EFFECT_UPDATE_DEFENSE)
	c:RegisterEffect(e4)
	local e5=Effect.CreateEffect(c)
	e5:SetType(EFFECT_TYPE_SINGLE)
	e5:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e5:SetRange(LOCATION_MZONE)
	e5:SetCode(EFFECT_IMMUNE_EFFECT)
	e5:SetCondition(c74010009.effcon)
	e5:SetLabel(4)
	e5:SetValue(c74010009.efilter)
	c:RegisterEffect(e5)
	--boost
	local e6=Effect.CreateEffect(c)
	e6:SetType(EFFECT_TYPE_FIELD)
	e6:SetCode(EFFECT_UPDATE_ATTACK)
	e6:SetRange(LOCATION_MZONE)
	e6:SetTargetRange(LOCATION_MZONE,0)
	e6:SetCondition(c74010009.effcon)
	e6:SetLabel(6)
	e6:SetTarget(c74010009.atktg)
	e6:SetValue(600)
	c:RegisterEffect(e6)
	local e7=e6:Clone()
	e7:SetCode(EFFECT_UPDATE_DEFENSE)
	c:RegisterEffect(e7)
	local e8=Effect.CreateEffect(c)
	e8:SetType(EFFECT_TYPE_FIELD)
	e8:SetRange(LOCATION_MZONE)
	e8:SetCode(EFFECT_IMMUNE_EFFECT)
	e8:SetTargetRange(LOCATION_MZONE,0)
	e8:SetCondition(c74010009.effcon)
	e8:SetLabel(6)
	e8:SetTarget(c74010009.atktg)
	e8:SetValue(c74010009.efilter)
	c:RegisterEffect(e8)
end
function c74010009.filter(c)
	return c:IsSetCard(0x3740)
end
function c74010009.effcon(e,tp,eg,ep,ev,re,r,rp)
    local g=Duel.GetMatchingGroup(c74010009.filter,tp,LOCATION_GRAVE,0,nil)
	local ct=g:GetClassCount(Card.GetCode)
	return ct>=e:GetLabel()
end
function c74010009.efilter(e,te)
	return te:GetOwnerPlayer()~=e:GetHandlerPlayer() and te:IsActiveType(TYPE_SPELL)
end
function c74010009.atktg(e,c)
	return c:IsSetCard(0x3740) and c~=e:GetHandler()
end